### ISSUE TITLE
broken here lol will try and fix

### ISSUE THREAD

**Issue by timmypidashev** [Ferret-Dev/BannerBot#1]
https://github.com/Ferret-Dev/BannerBot/blob/0836e05df33d6a4c223f34e880ee5aebdf8d8a76/bot.py#L18

error:
```bash
Ignoring exception in command banner:
Traceback (most recent call last):
  File "/home/timmy/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/timmy/BannerBot/test.py", line 65, in _banner
    await ctx.author.avatar.save(filename)
AttributeError: 'str' object has no attribute 'save'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/timmy/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/timmy/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/timmy/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'str' object has no attribute 'save'
```

**Comment by timmypidashev** [comment]
fixed
